### ISSUE TITLE
Can this be used directly in the browser?

### ISSUE THREAD

**Issue by atwright147** [liamja/modcheck.js#1]
Hi,

Can this be used directly in the browser?

I have built and browserified the code which successfully brings in the weightTable etc. Can I use this directly in the browser and ideally without require.js etc?

Many thanks,

Andy

P.S. Awesome library.

**Comment by liamja** [comment]
Hi Andy

I haven't tested this in the browser yet, but I'm aiming for it to be usable across both browser and headless environments.

Once this library has most of the VocaLink exceptions covered, I'll work on adding support for NPM/Bower and in-browser testing.

What you can do for now is use Browserify's _standalone_ output.

``` shell
$ npm build
$ browserify build/modcheck.js --standalone Modcheck > build/modcheck_bundle.js
```

``` html
<html>
    <head>
        <script src="build/modcheck_bundle.js"></script>
    </head>
    <body>
        <script>
            var modcheck = new Modcheck('66374958', '08-99-99');

            if (modcheck.check()) {
                console.log('This account number could potentially be registered to this sort code.');
            } else {
                console.log('This account number could NOT be registered to this sort code.');
            }
        </script>
    </body>
</html>
```

Hope that helps.

**Comment by atwright147** [comment]
That is awesome! Thank you :)

**Comment by atwright147** [comment]
Which exceptions are you missing?

**Comment by atwright147** [comment]
If you can let me know what needs doing, I and a couple of colleagues would be interested in seeing if we can help :)

**Comment by liamja** [comment]
Take a look at [the attached PDF](https://github.com/liamja/modcheck.js/files/35073/vocalink_-_validating_account_numbers_v2.80.pdf) (Section 5.2) that documents all of VocaLinks "Exceptions".

These need to be implemented for 100% compatibility, otherwise checks will fail when they should pass. You'll see I've made a start on a couple of them.

Any PRs implementing these exceptions are very welcome!
